<?php

return [
    'states' => [
        'Andhra Pradesh',
        'Arunachal Pradesh',
        'Assam',
        'Bihar',
        'Chhattisgarh',
        'Goa',
        'Gujarat',
        'Haryana',
        'Himachal Pradesh',
        'Jharkhand',
        'Karnataka',
        'Kerala',
        'Madhya Pradesh',
        'Maharashtra',
        'Manipur',
        'Meghalaya',
        'Mizoram',
        'Nagaland',
        'Odisha',
        'Punjab',
        'Rajasthan',
        'Sikkim',
        'Tamil Nadu',
        'Telangana',
        'Tripura',
        'Uttar Pradesh',
        'Uttarakhand',
        'West Bengal',
        'Delhi',
        'Jammu and Kashmir',
        'Ladakh',
        'Puducherry',
        'Chandigarh',
    ],

    'cities' => [
        'Gujarat' => [
            'Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Bhavnagar', 'Jamnagar',
            'Junagadh', 'Gandhinagar', 'Anand', 'Nadiad', 'Mehsana', 'Morbi',
            'Bharuch', 'Vapi', 'Navsari', 'Gota', 'Other',
        ],
        'Maharashtra' => ['Mumbai', 'Pune', 'Nagpur', 'Nashik', 'Thane', 'Other'],
        'Rajasthan' => ['Jaipur', 'Jodhpur', 'Udaipur', 'Kota', 'Ajmer', 'Other'],
        'Delhi' => ['New Delhi', 'North Delhi', 'South Delhi', 'East Delhi', 'West Delhi', 'Other'],
        'Karnataka' => ['Bengaluru', 'Mysuru', 'Hubballi', 'Mangaluru', 'Other'],
        'Tamil Nadu' => ['Chennai', 'Coimbatore', 'Madurai', 'Other'],
        'Uttar Pradesh' => ['Lucknow', 'Kanpur', 'Varanasi', 'Noida', 'Ghaziabad', 'Other'],
        'West Bengal' => ['Kolkata', 'Howrah', 'Durgapur', 'Other'],
        'Madhya Pradesh' => ['Bhopal', 'Indore', 'Gwalior', 'Jabalpur', 'Other'],
        'Punjab' => ['Chandigarh', 'Ludhiana', 'Amritsar', 'Jalandhar', 'Other'],
        'Haryana' => ['Gurugram', 'Faridabad', 'Panipat', 'Rohtak', 'Other'],
        'Bihar' => ['Patna', 'Gaya', 'Muzaffarpur', 'Other'],
        'Kerala' => ['Kochi', 'Thiruvananthapuram', 'Kozhikode', 'Other'],
        'Telangana' => ['Hyderabad', 'Warangal', 'Other'],
        'Andhra Pradesh' => ['Visakhapatnam', 'Vijayawada', 'Guntur', 'Other'],
        'Odisha' => ['Bhubaneswar', 'Cuttack', 'Other'],
        'Assam' => ['Guwahati', 'Silchar', 'Other'],
        'Jharkhand' => ['Ranchi', 'Jamshedpur', 'Other'],
        'Chhattisgarh' => ['Raipur', 'Bhilai', 'Other'],
        'Uttarakhand' => ['Dehradun', 'Haridwar', 'Other'],
        'Himachal Pradesh' => ['Shimla', 'Dharamshala', 'Other'],
        'Goa' => ['Panaji', 'Margao', 'Other'],
    ],
];
